Added minute labels
davidkarolyi/watch pull request #5
Opened 2021-02-19 20:28 UTC by maticsbalint

2021-02-20 09:37 UTC, davidkarolyi requested changes

2021-02-20 09:37 UTC, davidkarolyi commented on index.js
> +function getPositionFromDegs(degs) {
Let's use `degrees` instead of `degs` here to be consistent:

```js
function getPositionFromDegrees(degrees) {...}
```

2021-02-20 09:37 UTC, davidkarolyi commented on index.js
> +      console.log({ position, minutes, degrees });
We can remove this log from here

2021-02-21 09:24 UTC, maticsbalint commented on index.js
> +function getPositionFromDegs(degs) {
Done

2021-02-21 09:24 UTC, maticsbalint commented on index.js
> +      console.log({ position, minutes, degrees });
Done

2021-02-21 11:15 UTC, davidkarolyi approved these changes

2022-10-31 09:52 UTC, merged